### ISSUE TITLE
Separate the autosomic variant sites from the mitochondrial ones, if possible.

### ISSUE THREAD

**Issue by IgnasiLucas** [IgnasiLucas/mosquito#13]
See where we downloaded the reference genome from, and check if there is any annotation about the chromosomes. Or look at the names of the contigs, in case there is something obvious. The mitochondrial genome should correspond to a single contig. If the mitochondrial contig(s) is(are) known, then we need to split the vcf files from 2016-07-25 (and also the one from 2016-07-12) in a nuclear vcf and a mitochondrial vcf:
2016-07-12/bt_nuclear.vcf
2016-07-12/bt_mito.vcf
2016-07-25/fb_nuclear.vcf
2016-07-25/fb_mito.vcf,
for example. To extract specific positions or regions from a vcf, you can use bcftools, or vcftools. The latter is useful for many other things.

**Comment by mgmorant** [comment]
First I tried to sdo a BLAST to see the assembly but server of blast wasnt working. I also went to ensemble to search  Culex quinquefasciatus, but i didnt founf what I wanted because all i found was asembly to each supercontig and almost was rna coding, and there was not information about mithocondrial. Then I found in VectorBase information about mithoncondrial where there many genes but it is not useful: https://www.vectorbase.org/mitochondrial-genomes/culex-mitochondrial-genes?ref=seq&species=Culex_quinquefasciatus
Finally I search in NCBI and I found a shotgun sequence of one supercontig and what I can see is that there are many  small mithoncondrial genes(http://www.ncbi.nlm.nih.gov/nuccore/170056443), and I havent found any filter to separate it from the nuclear

**Comment by IgnasiLucas** [comment]
I found it. It's very easy. Nuclear chromosomes start all with 'supercontig3.', but there is one chromosome in the reference named 'Mt'. Even vcftools excluded that when testing for HWE, so there is little doubt that that is the mitochondrial genome. Try again, please. @mgmorant

**Comment by mgmorant** [comment]
Im working in 2016-07-12. I run it many times because Im doing many thing like separate molestus and pipiens, separate mitho/nuclear... and I think its the reason why I have errors. Now I run it to only obtain differents vcf to molestus and pipiens, and I have commented the rest of the options:

#Run a test of Hardy-Weinberg equilibrium 
#vcftools --vcf pipmosquito.vcf  --out HW  --hardy
#vcftools --vcf molmosquito.vcf  --out HW  --hardy

#seaprate nueclear/mihtocondrial
#bcftools  filter --exclude supercontig3 pipmosquito.vcf

I shouls do in the same readme.sh HW and in another one separate mithocondrial?
Anyway, Im not sure if is wanna work bcftools filter because I dont know if its gonna separate all the sequence of supercontig3

**Comment by mgmorant** [comment]
Finally I havent pushed it because I have a problem:

# Finally, we will be able to convert the BAM files obtained at the last step, to VCF.

# We will obtain a file with the information we called.

if [ ! -e Molmosquito.vcf ]; then
        ls -1 Mol*.bam > Molmosquito.txt
        samtools mpileup -gf reference.fa  Molmosquito.txt > molmosquito.mpileup
        bcftools view -Acg molmosquito.mpileup > molmosquito.vcf
fi

if [ ! -e Pipmosquito.vcf ]; then
       ls -1 Pip*.bam > Pipmosquito.txt
        for i in open('Pipmosquito.txt'); do

```
            samtools mpileup -gf reference.fa  # Finally, we will be able to convert the BAM files obtained at the last step, to VCF.
```

# We will obtain a file with the information we called.

if [ ! -e Molmosquito.vcf ]; then
        ls -1 Mol*.bam > Molmosquito.txt
        samtools mpileup -gf reference.fa  Molmosquito.txt > molmosquito.mpileup
        bcftools view -Acg molmosquito.mpileup > molmosquito.vcf
fi

if [ ! -e Pipmosquito.vcf ]; then
       ls -1 Pip*.bam > Pipmosquito.txt
        for i in open('Pipmosquito.txt'); do

```
            samtools mpileup -gf reference.fa # Finally, we will be able to convert the BAM files obtained at the last step, to VCF.
```

# We will obtain a file with the information we called.

if [ ! -e Molmosquito.vcf ]; then
        ls -1 Mol*.bam > Molmosquito.txt
        samtools mpileup -gf reference.fa  Molmosquito.txt > molmosquito.mpileup
        bcftools view -Acg molmosquito.mpileup > molmosquito.vcf
fi

if [ ! -e Pipmosquito.vcf ]; then
       ls -1 Pip*.bam > Pipmosquito.txt
        for i in open('Pipmosquito.txt'); do

```
            samtools mpileup -gf reference.fa  Pipmosquito.txt > pipmosquito.mpileup
             bcftools view -Acg pipmosquito.mpileup > pipmosquito.vcf
```

fi

> pipmosquito.mpileup
>                  bcftools view -Acg pipmosquito.mpileup > pipmosquito.vcf
> fi
> 
> pipmosquito.mpileup
>                  bcftools view -Acg pipmosquito.mpileup > pipmosquito.vcf
> fi

You want I separate them but if I do a file called Pipmosquito.txt I have to do a for and ope nthe file, but I think its a python script and im writting in bash so I think its not possible

**Comment by mgmorant** [comment]
sorry about the format

**Comment by mgmorant** [comment]
# We will obtain a file with the information we called.

if [ ! -e Molmosquito.vcf ]; then
        ls -1 Mol*.bam > Molmosquito.txt
        for i in open('Molmosquito.txt'):
                samtools mpileup -gf reference.fa  $i'.bam' > molmosquito.mpileup
                bcftools view -Acg molmosquito.mpileup > molmosquito.vcf
fi

if [ ! -e Pipmosquito.vcf ]; then
       ls -1 Pip*.bam > Pipmosquito.txt
        for i in open('Pipmosquito.txt'); do
                 samtools mpileup -gf reference.fa  $i'.bam' > pipmosquito.mpileup
                 bcftools view -Acg pipmosquito.mpileup > pipmosquito.vcf
fi

Thats the script I was referring before

**Comment by IgnasiLucas** [comment]
@mgmorant , it seems that you worked hard for this. I'm sorry to tell you that all that was not needed. This issue is about separating nuclear from mitochondrial variants, not about creating new vcf files with molestus and pipiens samples apart. The vcf file was perfect before, with all samples together. So, go back to the previous commit, and run the script again if necessary. Then, to separate nuclear variants from mitochondrial ones, you can use vcftools:

vcftools --vcf mosquito.vcf --chr Mt --out mosquito_mt --recode --recode-INFO-all
vcftools --vcf mosquito.vcf --not-chr Mt --out mosquito_nuc --recode --recode-INFO-all

However, I see that in 2016-07-25/test.vcf there are absolutely no mitochondrial variants. All of them are nuclear. Still, this may be contingent on the details of the generation of the vcf file. It is a good idea to record in the README.sh how you try to separate mitochondrial and nuclear sites, and how you reach the conclusion that all variant sites detected are nuclear.

By the way, it is true that in you attempt to separate molestus from pipiens you were mixing python and bash syntax. To iterate through a list of file names, in bash is very easy:

for i in `ls -1 Pip*.bam`; do
   ...
done

If the list of files was already in a file, you could do this:

for i in `cat archivos.txt`; do
   ...
done

Be aware that samtools mpileup combines the bam files given as input and create a compressed vcf file. To tell samtools mpileup to use all the bam files starting with Mol, for example, you can do:

samtools mpileup -gf reference.fa Mol*.bam > st.bcf

This program also accepts a list of input bam files (say, 'archivos.txt'):

samtools mpileup -gf reference.fa -b archivos.txt > st.bcf

Therefore, even if we had to create population-specific vcf files, it would not be necessary to run a for loop like the one that was giving you problems.

**Comment by mgmorant** [comment]
Finally, Im running again README.sh to obtain the vcf file again with the separation of mit/nuc. Also, I made a README2.sh, where I separate Mol/pip and also with the commands to know missing-site for each population
