### ISSUE TITLE
Run a test of Hardy-Weinberg equilibrium in nuclear variants

### ISSUE THREAD

**Issue by IgnasiLucas** [IgnasiLucas/mosquito#14]
You can use vcftools. Check the manual: http://vcftools.sourceforge.net/man_latest.html. You can do this as a new analysis. Run it separately for the variants identified with bcftools (done in 2016-07-12) and with freebayes (done in 2016-07-25).

**Comment by mgmorant** [comment]
I 've done it, but for all the samples because I couldnt separate nuclear-mithocondrial. The result in 2016-07-12  was done for many supercontigs but in 2016-07-25 only was done for one supercontig, and im not sure why this happens. I've looked if the file vcf is ok and it is...Maybe I should change min-mapping, but I think its not due to it.

I pushed both  README.sh and results.

**Comment by IgnasiLucas** [comment]
Thanks @mgmorant . See issue #4. Actually the vcf file is not ok. It only contains information of 6 individuals. Delete all results (archivos.txt, test.vcf, HW.hwe) and run again. Please, change the name of the vcf output to something more meaningful, like 'fb.vcf' (for freebayes, to distinguish this vcf from the one generated with samtools mpileup in 2016-07-12. I close this issue, because the HWE test is well implemented.
