### ISSUE TITLE
Increase the number of reads in the sample fastq in 2016-07-26

### ISSUE THREAD

**Issue by IgnasiLucas** [IgnasiLucas/mosquito#8]
Currently, there are only 10 sequences sampled from each individual, which is the default in sample_seqs. That's why the same number of clusters are generated under all values of wclust. We need at least 100000 sequences per sample. Get more (500000) if that does not produce a meaningful graph. Then plot the total number of clusters (Y axis) against the wclust value (X axis). To do this, I would write an R script (plot.R) and execute it from the README.sh. The plot.R script could be something like this:
# This reads the table in a data frame:

clusters <- read.table('summary_clust.txt', header=TRUE)
# This makes the variables in the data frame directly available in the work space:

attach(clusters)
# This opens the png file where to send the plot:

png(filename='molestus_clusters.png')
# This plots the first line:

plot(Wclust[muestra == 'Mol01_se'], total[muestra == 'Mol01_se'], type='l')
# This adds the second line. Do the same for subsequent ones:

lines(Wclust[muestra == 'Mol02_se'], total[muestra == 'Mol02_se'])
...
# Finally, it is necessary to close the png file:

dev.off()

Check help(plot) in R for details. Please, separate the pipiens plot in a different png file. @mgmorant

**Comment by mgmorant** [comment]
I increased the number of reads for each sample(100000 ), but the summary shows me the same results. Each sample have the same 'total' with the different wclust. Anyway, I've been trying to make the script. I wrote the script graph.R( very similar to yours) but I have mistakes about sintax. I've been trying to fix it but I do not know because I've never use it.

**Comment by mgmorant** [comment]
I am not sure if is syntax error or maybe I am executing it badly, because Im executing with './'
Ive been searching how to execute file.R but I havent found it so maybe its the problem. Anyway Ive push 2 files on my Github, one for molestus and another one for pipiens.

**Comment by mgmorant** [comment]
The error:
ARGUMENTO './graph.R' **ignorado**

R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R es un software libre y viene sin GARANTIA ALGUNA.
Usted puede redistribuirlo bajo ciertas circunstancias.
Escriba 'license()' o 'licence()' para detalles de distribucion.

R es un proyecto colaborativo con muchos contribuyentes.
Escriba 'contributors()' para obtener más información y
'citation()' para saber cómo citar R o paquetes de R en publicaciones.

Escriba 'demo()' para demostraciones, 'help()' para el sistema on-line de ayuda,
o 'help.start()' para abrir el sistema de ayuda HTML con su navegador.
Escriba 'q()' para salir de R.

ps: I also execut it since README.sh but its the same error

**Comment by IgnasiLucas** [comment]
Sorry for the bold font before. Github formats this messages.

I joined graph.R and Pipgraph.R in only one script, and I exectued it from README.sh calling R first: R --no-save < graph.R

I also noticed that only Molestus samples have more than 100000 reads. So, I modified the README.sh to use all reads from the pipiens samples. In any case, there should be many more clusters. Make sure you remove the fastq files and the summary_clusters.txt in 2016-07-26 before executing the README.sh.

**Comment by mgmorant** [comment]
I run it and I didnt obtain the graphs so I thought it was maybe because I hadnt removed clust.70,... so I removed it and It's being running the all morning. I think tomorrow I will obtain the graphs and if not, I will ask you because I have the same script as you.

**Comment by mgmorant** [comment]
it has finished but I cant see the .png. Do I need sth special to can see the graph?

**Comment by IgnasiLucas** [comment]
Currently, the server is running the X system, and you could open a png viewer, if you included the -X option when you logged in. However, I may remove the X system soon. Instead, you can scp the png files to your local computer and see them there. Nice graphs. Thanks, @mgmorant
